Repository openshift/ptp-operator, pull requests merged in 2019-10, with the labels that each got.

#1 Operator config API
  Makefile
  cmd/manager/main.go
  deploy/crds/ptp.openshift.io_nodeptpdevices_crd.yaml
  deploy/crds/ptp.openshift.io_operatorconfigs_crd.yaml
  deploy/crds/ptp.openshift.io_ptpcfgs_crd.yaml
  deploy/crds/ptp.openshift.io_v1_operatorconfig_cr.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/rolebinding.yaml
  go.mod
  hack/build.sh
  pkg/apis/ptp/v1/operatorconfig_types.go
  pkg/apis/ptp/v1/zz_generated.deepcopy.go
  pkg/apis/ptp/v1/zz_generated.openapi.go
  pkg/controller/add_operatorconfig.go
  pkg/controller/operatorconfig/operatorconfig_controller.go
  pkg/controller/ptpcfg/ptpcfg_controller.go
  pkg/controller/ptpcfg/recommend.go
  pkg/names/names.go
  vendor/modules.txt
Labels: size/XXL

#2 rename PtpCfg API to PtpConfig
  deploy/crds/ptp.openshift.io_ptpconfigs_crd.yaml
  deploy/crds/ptp.openshift.io_v1_nodeptpdevice_cr.yaml
  deploy/crds/ptp.openshift.io_v1_operatorconfig_cr.yaml
  deploy/crds/ptp.openshift.io_v1_ptpconfig_cr.yaml
  deploy/crds/ptp_v1_nodeptpdevice_cr.yaml
  hack/deploy-setup.sh
  hack/undeploy.sh
  manifests/4.3/ptp-operator.v4.3.0.clusterserviceversion.yaml
  manifests/4.3/ptp.openshift.io_nodeptpdevices_crd.yaml
  manifests/4.3/ptp.openshift.io_operatorconfigs_crd.yaml
  manifests/4.3/ptp.openshift.io_ptpconfigs_crd.yaml
  manifests/4.3/ptp_v1_ptpcfg_crd.yaml
  pkg/apis/ptp/v1/ptpconfig_types.go
  pkg/apis/ptp/v1/zz_generated.deepcopy.go
  pkg/apis/ptp/v1/zz_generated.openapi.go
  pkg/controller/add_ptpconfig.go
  pkg/controller/ptpconfig/ptpconfig_controller.go
  pkg/controller/ptpconfig/recommend.go
Labels: size/L

#4 Rename operator config API to PtpOperatorConfig
  cmd/manager/main.go
  deploy/crds/ptp.openshift.io_ptpoperatorconfigs_crd.yaml
  deploy/crds/ptp.openshift.io_v1_ptpoperatorconfig_cr.yaml
  hack/deploy-setup.sh
  hack/undeploy.sh
  manifests/4.3/ptp-operator.v4.3.0.clusterserviceversion.yaml
  manifests/4.3/ptp.openshift.io_ptpoperatorconfigs_crd.yaml
  pkg/apis/ptp/v1/ptpoperatorconfig_types.go
  pkg/apis/ptp/v1/zz_generated.deepcopy.go
  pkg/apis/ptp/v1/zz_generated.openapi.go
  pkg/controller/add_operatorconfig.go
  pkg/controller/ptpoperatorconfig/ptpoperatorconfig_controller.go
Labels: size/L

#7 change linuxptp-daemon image name to ptp
  hack/env.sh
  manifests/4.3/image-references
  manifests/4.3/ptp-operator.v4.3.0.clusterserviceversion.yaml
Labels: size/S

#9 Fix invalid YAML in manifests (fixes #8)
  manifests/4.3/ptp-operator.v4.3.0.clusterserviceversion.yaml
Labels: lgtm, size/XS
