Repository openshift/ptp-operator, pull requests merged in 2020-01, with the labels that each got.

#30 Deploy metrics for the linuxptp-daemon
  bindata/linuxptp/ptp-daemon.yaml
  deploy/clusterrole.yaml
  deploy/namespace.yaml
  go.mod
  manifests/4.4/ptp-operator.v4.4.0.clusterserviceversion.yaml
Labels: lgtm, size/L

#32 add Sebastian Scheinkman in OWNERs file
  OWNERS
Labels: lgtm, size/XS

#33 Fix cluster role for the operator
  deploy/clusterrole.yaml
  deploy/role.yaml
  manifests/4.4/ptp-operator.v4.4.0.clusterserviceversion.yaml
Labels: lgtm, size/XS

#19 BUG 1774078: fix env var name
  deploy/operator.yaml
  hack/env.sh
Labels: bugzilla/valid-bug, lgtm, size/XS

#34 add 4.5 manifests
  manifests/4.5/image-references
  manifests/4.5/ptp-operator.v4.5.0.clusterserviceversion.yaml
  manifests/4.5/ptp.openshift.io_nodeptpdevices_crd.yaml
  manifests/4.5/ptp.openshift.io_ptpconfigs_crd.yaml
  manifests/4.5/ptp.openshift.io_ptpoperatorconfigs_crd.yaml
  manifests/ptp-operator.package.yaml
  version/version.go
Labels: lgtm, size/L
