Repository openshift/ptp-operator, pull requests merged in 2020-09, with the labels that each got.

#70 Bug 1880990: Fix metric test
  test/ptp/ptp.go
Labels: bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#71 Bug 1880990: Choose the interfaces between master and slave.
  test/ptp/ptp.go
  test/utils/clean/clean.go
Labels: bugzilla/severity-high, bugzilla/valid-bug, lgtm

#72 Bug 1883794: Skip all of the tests if discovery fails.
  test/ptp/ptp.go
Labels: bugzilla/severity-medium, bugzilla/valid-bug, lgtm
