Repository openshift/ptp-operator, pull requests merged in 2021-11, with the labels that each got.

#140 Add validation webhook
  PROJECT
  api/v1/ptpconfig_webhook.go
  bindata/linuxptp/ptp-daemon.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/manager/manager.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  main.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/generated_expansion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
  vendor/k8s.io/client-go/util/retry/OWNERS
  vendor/k8s.io/client-go/util/retry/util.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/crd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/helper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/printer/ginkgo.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/printer/prow.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/flock_other.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/flock_unix.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/addr/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/certs/tinyca.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/apiserver.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/auth.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/etcd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/kubectl.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/plane.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/arguments.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/bin_path_finder.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/process.go
Labels: lgtm, ok-to-test

#142 Bug 2005926: Prometheus rules to use new metrics
  bindata/linuxptp/ptp-daemon.yaml
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#155 Remove the Z stream
  Makefile
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#149 Add ptp scheduling to PtpProfile crd
  api/v1/ptpconfig_types.go
  bundle/manifests/ptp.openshift.io_ptpconfigs.yaml
  config/crd/bases/ptp.openshift.io_ptpconfigs.yaml
  controllers/recommend.go
  manifests/stable/ptp.openshift.io_ptpconfigs.yaml
Labels: approved, lgtm

#161 Bug 2021152: change ImagePullPolicy
  bindata/linuxptp/ptp-daemon.yaml
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#162 Bug 2026223: Handle empty interface and config
  api/v1/ptpconfig_webhook.go
Labels: approved, lgtm

#158 Bug 2024731: Remove comparing check for discovered interface to configured interface list
  test/conformance/ptp/ptp.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#159 Add validation of scheduling policy
  api/v1/ptpconfig_types.go
  api/v1/ptpconfig_webhook.go
  api/v1/zz_generated.deepcopy.go
  bundle/manifests/ptp.openshift.io_ptpconfigs.yaml
  config/crd/bases/ptp.openshift.io_ptpconfigs.yaml
  manifests/stable/ptp.openshift.io_ptpconfigs.yaml
Labels: approved, lgtm
