Repository openshift/ptp-operator, pull requests merged in 2021-06, with the labels that each got.

#111 Add OLM bug workaround for workload partitioning
  manifests/4.8/ptp-operator.v4.8.0.clusterserviceversion.yaml
Labels: lgtm

#112 Bug 1957748: Add cpu and memory requests for the operator
  deploy/operator.yaml
  manifests/4.8/ptp-operator.v4.8.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#113 Bug 1957772: Fix openshift conformance test
  bindata/linuxptp/ptp-daemon.yaml
Labels: bugzilla/severity-low, bugzilla/valid-bug, lgtm
