Repository openshift/ptp-operator, pull requests merged in 2021-08, with the labels that each got.

#128 Add gofmt and format go code
  Makefile
  api/v1/ptpconfig_types.go
  controllers/recommend.go
  hack/gofmt.sh
Labels: approved, lgtm

#129 Bug 1991206: Add disconnected infrastructure-feature
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  manifests/4.9/ptp-operator.v4.9.0.clusterserviceversion.yaml
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#131 Bug 1993854: Added /var/run volume for sidecar
  bindata/linuxptp/ptp-daemon.yaml
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#132 Bug 1998598: added ptp event config manifest to 4.9
  manifests/4.9/ptp.openshift.io_ptpconfigs_crd.yaml
  manifests/4.9/ptp.openshift.io_ptpoperatorconfigs_crd.yaml
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent
