Repository openshift/ptp-operator, pull requests merged in 2022-09, with the labels that each got.

#220 Use privileged Daemonset library
  go.mod
  go.sum
  test/conformance/ptp/ptp.go
  test/utils/l2discovery/l2discovery.go
  vendor/github.com/test-network-function/privileged-daemonset/.gitignore
  vendor/github.com/test-network-function/privileged-daemonset/LICENSE
  vendor/github.com/test-network-function/privileged-daemonset/Makefile
  vendor/github.com/test-network-function/privileged-daemonset/README.md
  vendor/github.com/test-network-function/privileged-daemonset/main.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#217 Adding clock sync accuracy verification via metrics
  test/README.md
  test/conformance/ptp/ptp.go
  test/utils/l2discovery/l2discovery.go
  test/utils/metrics/metrics.go
  test/utils/pods/pods.go
  test/utils/testconfig/testconfig.go
Labels: approved, lgtm, ok-to-test

#224 adding check for when # of interfaces is less that what is needed for…
  test/conformance/ptp/ptp.go
  test/utils/l2discovery/l2discovery.go
Labels: approved, lgtm

#228 bugfix in ptpconfig discovery, fix for logging and additional logs
  api/v1/ptpconfig_webhook.go
  test/conformance/ptp/ptp.go
  test/conformance/test_suite_test.go
  test/utils/metrics/metrics.go
  test/utils/pods/pods.go
Labels: approved, lgtm

#231 add Nishant Parekh to owners
  OWNERS
Labels: approved, lgtm

#230 BUG OCPBUGS-1480: ptp operator csv references to 4.10 and 4.11 are updated to 4.12
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manager/env.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  hack/env.sh
  version/version.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug

#234 Fix controller-gen and operator-sdk versions
  Makefile
  bundle.Dockerfile
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  bundle/manifests/ptp.openshift.io_nodeptpdevices.yaml
  bundle/manifests/ptp.openshift.io_ptpconfigs.yaml
  bundle/manifests/ptp.openshift.io_ptpoperatorconfigs.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/ptp.openshift.io_nodeptpdevices.yaml
  config/crd/bases/ptp.openshift.io_ptpconfigs.yaml
  config/crd/bases/ptp.openshift.io_ptpoperatorconfigs.yaml
  config/rbac/role.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
  manifests/stable/ptp.openshift.io_nodeptpdevices.yaml
  manifests/stable/ptp.openshift.io_ptpconfigs.yaml
  manifests/stable/ptp.openshift.io_ptpoperatorconfigs.yaml
Labels: approved, lgtm

#232 Add supproort for HTTP transpoport
  README.md
  api/v1/ptpoperatorconfig_types.go
  bundle/manifests/ptp.openshift.io_ptpoperatorconfigs.yaml
  config/crd/bases/ptp.openshift.io_ptpoperatorconfigs.yaml
  manifests/stable/ptp.openshift.io_ptpoperatorconfigs.yaml
  test/conformance/ptp/ptp.go
Labels: approved, lgtm

#229 Bug OCPBUGS-1478: [release-4.11]update reference to ptp operator image from 4.10 to 4.11
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  hack/env.sh
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#237 export restartPtpDaemon function for use in cnf-feature-deploy
  test/conformance/ptp/ptp.go
Labels: approved, lgtm

#239 Downgrade to golang 1.18
  Dockerfile
  go.mod
Labels: approved, lgtm

#245 Fix skipRange with double quotes
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: approved, lgtm
