Repository openshift/ptp-operator, pull requests merged in 2022-02, with the labels that each got.

#175 [release 4.9] Bug 2055272:change ImagePullPolicy
  bindata/linuxptp/ptp-daemon.yaml
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  manifests/4.9/ptp-operator.v4.9.0.clusterserviceversion.yaml
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#174 Bug 2051611: Remove validating summary_interval matches logSyncInterval
  api/v1/ptpconfig_webhook.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#173 Updated bundle manifest for 4.11
  Makefile
  bundle.Dockerfile
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/env.yaml
  config/manager/kustomization.yaml
  manifests/image-references
  manifests/ptp-operator.package.yaml
  version/version.go
Labels: approved, lgtm
