Repository openshift/ptp-operator, pull requests merged in 2022-12, with the labels that each got.

#270 Bug OCPBUGS-3891: Adding back SKIP_INTERFACES feature
  go.mod
  go.sum
  test/conformance/serial/ptp.go
  test/pkg/ptphelper/ptphelper.go
  vendor/github.com/test-network-function/l2discovery-lib/l2lib.go
  vendor/github.com/test-network-function/privileged-daemonset/.golangci.yml
  vendor/github.com/test-network-function/privileged-daemonset/main.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug

#274 Bug OCPBUGS-4434: Filtering Virtual interfaces from list of viable ptp interfaces
  go.mod
  go.sum
  vendor/github.com/test-network-function/l2discovery-lib/l2lib.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug

#279 Refinement of parallel test framework code
  go.mod
  go.sum
  hack/run-functests.sh
  test/conformance/config/ptptestconfig.go
  test/conformance/config/ptptestconfig.yaml
  test/conformance/config/ptptestconfig_test.go
  test/conformance/config/testdata/cfg1.yaml
  test/conformance/config/testdata/cfg2.yaml
  test/conformance/parallel/parallel_suite_test.go
  test/conformance/parallel/ptp.go
  vendor/github.com/creasty/defaults/.gitignore
  vendor/github.com/creasty/defaults/LICENSE
  vendor/github.com/creasty/defaults/Makefile
  vendor/github.com/creasty/defaults/README.md
  vendor/github.com/creasty/defaults/defaults.go
  vendor/github.com/creasty/defaults/setter.go
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/reporters/default_reporter.go
  vendor/github.com/onsi/ginkgo/v2/types/config.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/golang.org/x/sys/unix/sockcmsg_unix.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/modules.txt
Labels: approved, lgtm

#284 OCPBUGS-2806: Add logReduce
  README.md
  api/v1/ptpconfig_webhook.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/severity-important, jira/valid-bug
