Repository openshift/ptp-operator, pull requests merged in 2022-10, with the labels that each got.

#244 Enhancement of ptp nic details
  go.mod
  go.sum
  test/conformance/ptp/ptp.go
  vendor/github.com/test-network-function/l2discovery-exports/libexports.go
  vendor/github.com/test-network-function/l2discovery-lib/l2lib.go
  vendor/modules.txt
Labels: approved, lgtm

#251 go 1.19 needs to update gofmt changes
  api/v1/groupversion_info.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
Labels: approved, lgtm

#238 Add labels to fix pod-security issue in 4.12
  config/manager/manager.yaml
Labels: approved, lgtm

#255 Fix make bundle for skipRange with double quotes
  Makefile
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#256 Setup function to initialize client
  test/pkg/client/clients.go
Labels: approved, lgtm

#248 Refactoring for testing NodePtpDevice api
  go.mod
  go.sum
  test/conformance/ptp/ptp.go
  test/pkg/ptphelper/ptphelper.go
  test/pkg/ptptesthelper/ptptesthelper.go
  vendor/github.com/test-network-function/l2discovery-lib/l2lib.go
  vendor/modules.txt
Labels: approved, lgtm

#253 Proposal for temporary ginkgo v1 custom reporter
  test/conformance/test_suite_test.go
  test/pkg/ginkgo_reporter/ptp_reporter.go
  test/pkg/ginkgo_reporter/ptp_reporter_test.go
Labels: approved, lgtm, ok-to-test

#249 Bug OCPBUGS-2042: Fix skipRange with double quotes
  Makefile
  bundle.Dockerfile
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  bundle/manifests/ptp.openshift.io_nodeptpdevices.yaml
  bundle/manifests/ptp.openshift.io_ptpconfigs.yaml
  bundle/manifests/ptp.openshift.io_ptpoperatorconfigs.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/ptp.openshift.io_nodeptpdevices.yaml
  config/crd/bases/ptp.openshift.io_ptpconfigs.yaml
  config/crd/bases/ptp.openshift.io_ptpoperatorconfigs.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/mitchellh/reflectwalk/go.mod
  vendor/gopkg.in/yaml.v2/go.sum
  vendor/gopkg.in/yaml.v3/go.mod
  vendor/gopkg.in/yaml.v3/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/config/v1alpha1/zz_generated.deepcopy.go
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug
