Repository openshift/ptp-operator, pull requests merged in 2023-03, with the labels that each got.

#314 update go19 and ocp 4.13
  Dockerfile
Labels: approved, lgtm

#316 fix for junit file not recorded and updated README. Log fixes.
  hack/run-functests.sh
  test/conformance/parallel/ptp.go
Labels: approved, lgtm

#318 CPU Usage test case improvements
  go.mod
  go.sum
  test/README.md
  test/conformance/config/cpu_usage_test_config.go
  test/conformance/config/ptptestconfig.go
  test/conformance/config/ptptestconfig.yaml
  test/conformance/config/ptptestconfig_test.go
  test/conformance/parallel/parallel_suite_test.go
  test/conformance/parallel/ptp.go
  test/pkg/client/clients.go
  test/pkg/pods/pods.go
  test/pkg/ptphelper/ptphelper.go
  test/pkg/ptptesthelper/prometheus.go
  test/pkg/ptptesthelper/ptptesthelper.go
  test/pkg/testconfig/testconfig.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/LICENSE
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1/alertmanager_config_conversion.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1/validation.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1beta1/conversion_from.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1beta1/conversion_to.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1beta1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1beta1/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1beta1/validation.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/LICENSE
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/scheme/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/scheme/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/alertmanager.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/generated_expansion.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/monitoring_client.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/podmonitor.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/probe.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/prometheus.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/prometheusrule.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/servicemonitor.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/thanosruler.go
  vendor/modules.txt
Labels: approved, lgtm

#317 Bug: OCPBUGS-4947: Fixup building bundle in 4.12
  Makefile
  api/v1/zz_generated.deepcopy.go
  manifests/stable/ptp-operator.clusterserviceversion.yaml
  manifests/stable/ptp.openshift.io_ptpconfigs.yaml
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#315 Bug OCPBUGS-2832: mount cloud-event-proxy store to pvc for http
  bindata/linuxptp/ptp-daemon.yaml
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/custom/rbac.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/valid-reference

#323 update issues identified by go vet
  test/pkg/pods/pods.go
Labels: approved, lgtm

#326 Add storageType and set default transportHost to HTTP
  PROJECT
  README.md
  api/v1/ptpconfig_webhook.go
  api/v1/ptpoperatorconfig_types.go
  api/v1/ptpoperatorconfig_webhook.go
  bindata/linuxptp/ptp-daemon.yaml
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  bundle/manifests/ptp.openshift.io_ptpoperatorconfigs.yaml
  bundle/manifests/webhook-service_v1_service.yaml
  config/crd/bases/ptp.openshift.io_ptpoperatorconfigs.yaml
  config/custom/rbac.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/webhook/kustomization.yaml
  config/webhook/manifests.yaml
  config/webhook/patches/patch_webhook_configuration.yaml
  config/webhook/service.yaml
  controllers/ptpoperatorconfig_controller.go
  main.go
  manifests/stable/ptp-operator.clusterserviceversion.yaml
  manifests/stable/ptp.openshift.io_ptpoperatorconfigs.yaml
  manifests/stable/webhook-service_v1_service.yaml
Labels: approved, lgtm

#319 Developer documentation
  test/DEVELOPERS.md
  test/conformance/parallel/event-output.csv
  test/conformance/parallel/ptp.go
  test/conformance/serial/prometheus.go
  test/conformance/test.go
  test/doc/bcoverview.svg
  test/doc/dualnicbcoverview.svg
  test/doc/ocoverview.svg
  test/doc/ptpeventsinprocesscommunication.svg
  test/doc/ptpeventsnosidecar.svg
  test/doc/ptpeventswithconsumersidecar.svg
  test/doc/ptptestconfig.svg
  test/pkg/metrics/prometheus.go
  test/pkg/ptptesthelper/ptptesthelper.go
Labels: approved, lgtm

#328 Fixes - l2discovery LAG support and unsubscribe event wrong host
  go.mod
  go.sum
  test/conformance/serial/ptp.go
  test/pkg/pods/pods.go
  vendor/github.com/redhat-cne/channel-pubsub/pubsublib.go
  vendor/github.com/redhat-cne/ptp-listener-lib/listenerlib.go
  vendor/github.com/test-network-function/l2discovery-exports/libexports.go
  vendor/github.com/test-network-function/l2discovery-lib/l2lib.go
  vendor/github.com/test-network-function/l2discovery-lib/pkg/pods/pods.go
  vendor/github.com/test-network-function/privileged-daemonset/.golangci.yml
  vendor/github.com/test-network-function/privileged-daemonset/Makefile
  vendor/github.com/test-network-function/privileged-daemonset/main.go
  vendor/modules.txt
Labels: approved, lgtm
