Repository openshift/ptp-operator, pull requests merged in 2023-07, with the labels that each got.

#360 Bug OCPBUGS-15317: set StorageType to emptyDir for HTTP transport
  api/v1/ptpoperatorconfig_webhook.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#359 CNF-7015: Add basic unit test for plugin framework
  hack/run-functests.sh
  test/conformance/serial/ptp.go
  test/pkg/ptphelper/ptphelper.go
Labels: approved, lgtm, jira/valid-reference

#362 fix nightly CI tests failures
  test/pkg/ptphelper/ptphelper.go
Labels: approved, lgtm

#352 OCPBUGS-14993: update master to 4.14 references
  Dockerfile
  Makefile
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manager/env.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  go.mod
  hack/env.sh
  manifests/image-references
  manifests/ptp-operator.package.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#363 [release-4.13] Bug OCPBUGS-16391: Add configmap support for cloud events
  api/v1/ptpoperatorconfig_webhook.go
  bindata/linuxptp/ptp-daemon.yaml
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/custom/rbac.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#364 [release-4.12] Bug OCPBUGS-16706: Add configmap support for cloud events
  api/v1/ptpoperatorconfig_webhook.go
  bindata/linuxptp/ptp-daemon.yaml
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/custom/rbac.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#365 fix Dockerfile for golang-1.20
  Dockerfile
  Dockerfile.ci
Labels: approved, lgtm
