Repository openshift/ptp-operator, pull requests merged in 2023-11, with the labels that each got.

#395 add ci test for lease interval
  test/pkg/ptphelper/ptphelper.go
  test/validation/tests/validation.go
Labels: approved, lgtm

#393 [release-4.14] Bug OCPBUGS-21540: disable http2 in kube-rbac-proxy
  bindata/linuxptp/ptp-daemon.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#397 [release-4.14] Bug OCPBUGS-22695: fix SNO lease duration and restore namespace
  main.go
  test/pkg/ptphelper/ptphelper.go
  test/validation/tests/validation.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#396 OCPBUGS-22934: PTP operator needs infrastructure annotations to pass CVP tests
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#400 [release-4.14] Bug OCPBUGS-23035: add new infra annotations
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#378 [release-4.13] Bug OCPBUGS-21595: add suggested-namespace annotation
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#402 [release-4.13] Bug OCPBUGS-23405: add new infra annotations
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#382 [release-4.12] OCPBUGS-20185: ptp4l process restarted unexpected with dual NIC boundary clocks configured
  controllers/recommend.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#379 [release-4.12] Bug OCPBUGS-21596: add suggested-namespace annotation
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#403 [release-4.12] Bug OCPBUGS-23415: add new infra annotations
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#405 Bug OCPBUGS-23790: set LeaderElectionReleaseOnCancel to speed up recovery
  main.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference
