Repository openshift/ptp-operator, pull requests merged in 2023-04, with the labels that each got.

#333 using non-default namespace for privileged-daemonset
  test/pkg/consts.go
  test/pkg/ptptesthelper/ptptesthelper.go
Labels: approved, lgtm

#329 [release-4.13] Bug OCPBUGS-2832: Add storageType, set default transportHost to HTTP
  PROJECT
  README.md
  api/v1/ptpconfig_webhook.go
  api/v1/ptpoperatorconfig_types.go
  api/v1/ptpoperatorconfig_webhook.go
  bindata/linuxptp/ptp-daemon.yaml
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  bundle/manifests/ptp.openshift.io_ptpoperatorconfigs.yaml
  bundle/manifests/webhook-service_v1_service.yaml
  config/crd/bases/ptp.openshift.io_ptpoperatorconfigs.yaml
  config/custom/rbac.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/webhook/kustomization.yaml
  config/webhook/manifests.yaml
  config/webhook/patches/patch_webhook_configuration.yaml
  config/webhook/service.yaml
  controllers/ptpoperatorconfig_controller.go
  main.go
  manifests/stable/ptp-operator.clusterserviceversion.yaml
  manifests/stable/ptp.openshift.io_ptpoperatorconfigs.yaml
  manifests/stable/webhook-service_v1_service.yaml
  test/pkg/pods/pods.go
  test/pkg/ptphelper/ptphelper.go
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#336 OCPBUGS-8249: Added pods rbac to bundle to support HTTP events on multiple nodes
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#337 Bug OCPBUGS-11822: Fix webhook Spec.EventConfig null pointer
  api/v1/ptpoperatorconfig_webhook.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/valid-reference

#341 OCPBUGS-11137: Add configmap to store subscriber info as a storage type - To prevent loss of subscribers
  bindata/linuxptp/ptp-daemon.yaml
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/custom/rbac.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: bugzilla/valid-bug, approved, lgtm, jira/valid-bug, jira/valid-reference
