Repository openshift/ptp-operator, pull requests merged in 2023-02, with the labels that each got.

#297 [release-4.12] BUG OCPBUGS-6076: Update WATCH_NAMESPACE
  Makefile
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#299 [release-4.12] BUG OCPBUGS-6076: turn on logs on operator
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#298 turn on logs on operator
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#295 [BUGFIX][CONFORMANCE]: Fix incorrect PTP config created when there is not enough resources to run the selected mode (dualnicbc)
  test/conformance/parallel/parallel_suite_test.go
  test/conformance/serial/ptp.go
  test/pkg/testconfig/testconfig.go
Labels: approved, lgtm

#301 Outage recovery : Fix the check on pod emptiness
  test/pkg/ptptesthelper/ptptesthelper.go
Labels: approved, lgtm

#303 [release-4.11] Bug OCPBUGS-4754: Fix amq race condition
  Makefile
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/ptpoperatorconfig_controller.go
  main.go
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#282 Adding multi-node support for ptp events
  bindata/linuxptp/event-service.yaml
  bindata/linuxptp/ptp-daemon.yaml
  config/custom/rbac.yaml
  controllers/ptpoperatorconfig_controller.go
Labels: approved, lgtm

#300 add plugins to ptpconfig api
  api/v1/nodeptpdevice_types.go
  api/v1/ptpconfig_types.go
  api/v1/ptpoperatorconfig_types.go
  api/v1/zz_generated.deepcopy.go
  bindata/linuxptp/ptp-daemon.yaml
  bundle/manifests/ptp.openshift.io_nodeptpdevices.yaml
  bundle/manifests/ptp.openshift.io_ptpconfigs.yaml
  bundle/manifests/ptp.openshift.io_ptpoperatorconfigs.yaml
  config/crd/bases/ptp.openshift.io_nodeptpdevices.yaml
  config/crd/bases/ptp.openshift.io_ptpconfigs.yaml
  config/crd/bases/ptp.openshift.io_ptpoperatorconfigs.yaml
  controllers/ptpoperatorconfig_controller.go
Labels: approved, lgtm

#302 [release-4.10] OCPBUGS-4755: Fix amq race condition
  Makefile
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/ptpoperatorconfig_controller.go
  main.go
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#286 CPU utilization test case for the parallel test suite.
  test/conformance/config/ptptestconfig.go
  test/conformance/parallel/ptp.go
  test/conformance/serial/prometheus.go
  test/pkg/consts.go
  test/pkg/pods/pods.go
  test/pkg/ptptesthelper/prometheus.go
  test/pkg/ptptesthelper/ptptesthelper.go
Labels: approved, lgtm

#306 BUG OCPBUGS-7441: Match the O-RAN specification for the ocloudNotifications URI
  test/conformance/serial/ptp.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#307 Fix building bundle
  Makefile
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
  manifests/stable/ptp.openshift.io_nodeptpdevices.yaml
  manifests/stable/ptp.openshift.io_ptpconfigs.yaml
  manifests/stable/ptp.openshift.io_ptpoperatorconfigs.yaml
Labels: approved, lgtm

#305 Bash script to get the cpu usage of ptp containers.
  test/scripts/ptp-cpu-usage.sh
Labels: approved, lgtm

#309 BUG OCPBUGS-7611: Fix amq race condition failing on service check and repeating same check on every reconcile
  controllers/ptpoperatorconfig_controller.go
  main.go
Labels: bugzilla/valid-bug, approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference

#310 [release 4.12] OCPBUGS-7728: Fix amq race condition failing on service check and repeating same check on every reconcile
  controllers/ptpoperatorconfig_controller.go
  main.go
Labels: bugzilla/valid-bug, approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#257 Minor logs improvements
  controllers/ptpoperatorconfig_controller.go
Labels: approved, lgtm, ok-to-test

#313 Enable e810 plugin by default
  api/v1/ptpoperatorconfig_types.go
  api/v1/zz_generated.deepcopy.go
  bundle/manifests/ptp.openshift.io_ptpoperatorconfigs.yaml
  config/crd/bases/ptp.openshift.io_ptpoperatorconfigs.yaml
  controllers/ptpoperatorconfig_controller.go
  manifests/stable/ptp.openshift.io_ptpoperatorconfigs.yaml
Labels: approved, lgtm
