Repository openshift/ptp-operator, pull requests merged in 2024-11, with the labels that each got.

#549 Add support for fips
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#548 CNF-14533: Event Based Additional Tests
  go.mod
  go.sum
  test/conformance/serial/ptp.go
  test/pkg/testconfig/testconfig.go
  vendor/github.com/facebook/time/LICENSE
  vendor/github.com/facebook/time/hostendian/hostendian.go
  vendor/github.com/facebook/time/ptp/protocol/doc.go
  vendor/github.com/facebook/time/ptp/protocol/management.go
  vendor/github.com/facebook/time/ptp/protocol/management_client.go
  vendor/github.com/facebook/time/ptp/protocol/management_tlvs.go
  vendor/github.com/facebook/time/ptp/protocol/protocol.go
  vendor/github.com/facebook/time/ptp/protocol/ptp4l.go
  vendor/github.com/facebook/time/ptp/protocol/tlvs.go
  vendor/github.com/facebook/time/ptp/protocol/types.go
  vendor/github.com/facebook/time/ptp/protocol/unicast.go
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_flags.go
  vendor/github.com/golang/glog/internal/logsink/logsink.go
  vendor/github.com/golang/glog/internal/logsink/logsink_fatal.go
  vendor/github.com/golang/glog/internal/stackdump/stackdump.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#547 CNF-14531: Tests for loss of GNSS signal and holdover
  test/conformance/serial/ptp.go
Labels: approved, jira/valid-reference
