Repository openshift/ptp-operator, pull requests merged in 2024-02, with the labels that each got.

#375 CNF-9844: increase timeout for outage recovery test to avoid spurious failures
  test/pkg/ptptesthelper/ptptesthelper.go
Labels: approved, lgtm, jira/valid-reference

#430 Increase PrometheusQueryRetries to 30
  test/pkg/metrics/prometheus.go
Labels: approved, lgtm

#431 OCPBUGS-28344: SAST scan issues exclude test code in snyk
  .snyk
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#437 Increase wait for PushInitialEvent from 20 to 60
  test/conformance/parallel/ptp.go
Labels: approved, lgtm

#446 Update operator version from 4.15 to 4.16
  Makefile
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manager/env.yaml
  config/manager/kustomization.yaml
  hack/env.sh
  manifests/stable/ptp-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm

#445 OCPBUGS-29634: fix ci issues
  hack/run-functests.sh
  test/conformance/parallel/ptp.go
  test/conformance/serial/prometheus.go
  test/pkg/clean/clean.go
  test/pkg/event/event.go
  test/pkg/logging/logging.go
  test/pkg/metrics/prometheus.go
  test/pkg/namespaces/namespaces.go
  test/pkg/ptptesthelper/ptptesthelper.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#447 fix go installation in test script
  hack/run-functests.sh
Labels: approved, lgtm

#448 fix go version used in ci job
  hack/run-functests.sh
Labels: approved, lgtm

#449 OCPBUGS-29634: fix CPU Utilization soak test
  test/conformance/config/ptptestconfig.yaml
  test/conformance/parallel/ptp.go
  test/conformance/serial/prometheus.go
  test/pkg/metrics/prometheus.go
  test/pkg/ptptesthelper/ptptesthelper.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
