Repository openshift/ptp-operator, pull requests merged in 2024-04, with the labels that each got.

#463 CNF-11962: PTP CI TC timedout: Event based tests PTP Slave Clock Sync
  test/pkg/event/event.go
Labels: approved, lgtm, jira/valid-reference

#464 temporarily disable sync test
  test/conformance/parallel/ptp.go
Labels: approved, lgtm

#465 CI: fix timeout in PushInitialEvent
  test/pkg/event/event.go
Labels: approved, lgtm

#466 OCPBUGS-32442: Need a ptpOperatorConfig webhook to prevent users from creating a new event config
  api/v1/ptpoperatorconfig_webhook.go
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/webhook/manifests.yaml
  main.go
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
