Repository openshift/ptp-operator, pull requests merged in 2024-03, with the labels that each got.

#452 OCPBUGS-29472: PTP service annotated with certificate error
  bindata/linuxptp/event-service.yaml
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#434 [release-4.15] OCPBUGS-28362: exclude test code in snyk
  .snyk
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#435 [release-4.14] OCPBUGS-27971: exclude test code in snyk
  .snyk
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#440 [release-4.13] OCPBUGS-26989: SAST scan issues exclude test code in snyk
  .snyk
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#441 [release-4.12] OCPBUGS-28513: SAST scan issues exclude test code in snyk
  .snyk
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#453 CNF-11459: update script to install go version using the new telco-runner image.
  hack/run-functests.sh
Labels: approved, lgtm, jira/valid-reference

#456 include haprofiles under PTPSettings
  README.md
  api/v1/ptpconfig_webhook.go
Labels: approved, lgtm

#457 add replaces in csv
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#458 fix install controller-gen in ci
  Makefile
Labels: approved, lgtm

#460 OCPBUGS-30648: PTP CI TC Failure: PTP socket sharing between pods Run pmc in a new pod on the slave node Should be able to sync using a uds
  test/conformance/serial/ptp.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#461 remove spec.replaces from csv
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#462 OCPBUGS-30427: update sdk-go
  .snyk
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/v2/alias.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/encoding.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/event_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/format/format.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/spec/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/to_event.go
  vendor/github.com/cloudevents/sdk-go/v2/client/client.go
  vendor/github.com/cloudevents/sdk-go/v2/client/http_receiver.go
  vendor/github.com/cloudevents/sdk-go/v2/client/invoker.go
  vendor/github.com/cloudevents/sdk-go/v2/client/options.go
  vendor/github.com/cloudevents/sdk-go/v2/client/receiver.go
  vendor/github.com/cloudevents/sdk-go/v2/context/delegating.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_data.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_unmarshal.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1.go
  vendor/github.com/cloudevents/sdk-go/v2/event/extensions.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/abuse_protection.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/context.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/message.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/options.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol_lifecycle.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol_rate.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol_retry.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/utility.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/write_request.go
  vendor/github.com/cloudevents/sdk-go/v2/types/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/types/value.go
  vendor/github.com/google/uuid/.travis.yml
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version6.go
  vendor/github.com/google/uuid/version7.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_ce.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_data.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/event_writer.go
  vendor/github.com/redhat-cne/sdk-go/pkg/event/redfish/event_marshal.go
  vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub.go
  vendor/github.com/redhat-cne/sdk-go/pkg/types/value.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
