Repository openshift/ptp-operator, pull requests merged in 2024-06, with the labels that each got.

#470 OCPBUGS-33597: Add automatic leap file update via configmap
  bindata/linuxptp/ptp-daemon.yaml
  controllers/ptpoperatorconfig_controller.go
  pkg/names/names.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#480 CNF-13146: ci test: fix message_tag matching with {level}
  test/pkg/ptphelper/ptphelper.go
Labels: approved, lgtm, jira/valid-reference

#479 CNF-12093: remove amq and pvc
  README.md
  api/v1/ptpoperatorconfig_types.go
  api/v1/ptpoperatorconfig_webhook.go
  bindata/linuxptp/ptp-daemon.yaml
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  bundle/manifests/ptp.openshift.io_ptpoperatorconfigs.yaml
  config/crd/bases/ptp.openshift.io_ptpoperatorconfigs.yaml
  config/custom/rbac.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/ptpoperatorconfig_controller.go
  main.go
  manifests/stable/ptp-operator.clusterserviceversion.yaml
  manifests/stable/ptp.openshift.io_ptpoperatorconfigs.yaml
  test/DEVELOPERS.md
Labels: approved, lgtm, jira/valid-reference

#482 update ptp operator to 4.17
  Dockerfile
  Dockerfile.ci
  Makefile
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manager/env.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  hack/env.sh
  manifests/image-references
  manifests/ptp-operator.package.yaml
  manifests/stable/ptp-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm

#483 Add synceConf and SynceOpts to ptpconfig
  README.md
  api/v1/ptpconfig_types.go
  api/v1/zz_generated.deepcopy.go
  bundle/manifests/ptp.openshift.io_ptpconfigs.yaml
  config/crd/bases/ptp.openshift.io_ptpconfigs.yaml
  manifests/stable/ptp.openshift.io_ptpconfigs.yaml
Labels: approved, lgtm

#485 CNF-12834 CNF-11822 update origin-kube-rbac-proxy image and fix CI
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  config/manager/env.yaml
  manifests/image-references
  manifests/stable/ptp-operator.clusterserviceversion.yaml
  test/conformance/parallel/ptp.go
  test/conformance/serial/ptp.go
Labels: approved, lgtm

#484 fix security test
  .snyk
Labels: approved, lgtm

#486 CNF-12095: Introduce event service API version
  api/v1/ptpoperatorconfig_types.go
  bindata/linuxptp/ptp-daemon.yaml
  bundle/manifests/ptp-operator.clusterserviceversion.yaml
  bundle/manifests/ptp.openshift.io_ptpoperatorconfigs.yaml
  config/crd/bases/ptp.openshift.io_ptpoperatorconfigs.yaml
  config/manifests/bases/ptp-operator.clusterserviceversion.yaml
  controllers/ptpoperatorconfig_controller.go
  manifests/stable/ptp-operator.clusterserviceversion.yaml
  manifests/stable/ptp.openshift.io_ptpoperatorconfigs.yaml
Labels: approved, lgtm, jira/valid-reference

#491 CNF-13356: CI fix syncstate timeout
  test/conformance/parallel/ptp.go
Labels: approved, lgtm, jira/valid-reference

#489 update syncEOpts and syncEConf to syncE4lOpts and syncE4lConf
  README.md
  api/v1/ptpconfig_types.go
  api/v1/zz_generated.deepcopy.go
  bundle/manifests/ptp.openshift.io_ptpconfigs.yaml
  config/crd/bases/ptp.openshift.io_ptpconfigs.yaml
  manifests/stable/ptp.openshift.io_ptpconfigs.yaml
Labels: approved, lgtm

#477 OCPBUGS-35190: add leap file updates documentation
  README.md
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
