Repository openshift/ptp-operator, pull requests merged in 2025-03, with the labels that each got.

#577 Upstream to downstream staging main
  COMMUNITY.md
  controllers/ptpoperatorconfig_controller.go
  go.mod
  go.sum
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_file_linux.go
  vendor/github.com/golang/glog/glog_file_nonwindows.go
  vendor/github.com/golang/glog/glog_file_other.go
  vendor/github.com/golang/glog/glog_file_posix.go
  vendor/github.com/golang/glog/glog_file_windows.go
  vendor/github.com/golang/glog/glog_flags.go
  vendor/github.com/golang/glog/internal/logsink/logsink.go
  vendor/modules.txt
Labels: approved, lgtm

#579 Upstream to downstream staging main
  bindata/linuxptp/ptp-daemon.yaml
  hack/build.sh
  test/DEVELOPERS.md
  test/pkg/event/event.go
Labels: approved, lgtm

#580 [release-4.14] OCPBUGS-53021: fix compile error in CI
  .snyk
  Dockerfile
  Dockerfile.ci
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#583 OCPBUGS-53021: Revert "fix compile error in CI"
  Dockerfile
  Dockerfile.ci
Labels: approved, lgtm, cherry-pick-approved, ok-to-test, backport-risk-assessed, jira/valid-bug, jira/valid-reference
